"use client";
import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import AuthModal from '@/components/AuthModal';
import { Calendar, Filter, Search, FileText, TrendingUp, ArrowRight, Clock, Users } from 'lucide-react';
import { cn } from '@/lib/utils';

interface BriefSummary {
  id: string;
  title: string;
  summary: string;
  type: 'EXECUTIVE_BRIEF' | 'STRATEGIC_REPORT';
  publishedAt: string;
  readTime: number;
  sources: number;
  topics: string[];
}

export default function BriefsPage() {
  const router = useRouter();
  const [showAuthModal, setShowAuthModal] = useState(false);
  const [briefs, setBriefs] = useState<BriefSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState<'all' | 'executive' | 'strategic'>('all');
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  useEffect(() => {
    fetchBriefs();
  }, [page, filterType, searchTerm]);

  const fetchBriefs = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({
        page: page.toString(),
        limit: '12',
        ...(filterType !== 'all' && { type: filterType }),
        ...(searchTerm && { search: searchTerm }),
      });

      const response = await fetch(`/api/public/briefs?${params}`);
      const data = await response.json();
      
      setBriefs(data.briefs || []);
      setTotalPages(data.totalPages || 1);
    } catch (error) {
      console.error('Failed to fetch briefs:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleReadFull = (briefId: string) => {
    // Trigger auth modal for upgrade
    setShowAuthModal(true);
  };

  const filteredBriefs = briefs.filter(brief => {
    const matchesSearch = !searchTerm || 
      brief.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      brief.summary.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesType = filterType === 'all' || 
      (filterType === 'executive' && brief.type === 'EXECUTIVE_BRIEF') ||
      (filterType === 'strategic' && brief.type === 'STRATEGIC_REPORT');
    
    return matchesSearch && matchesType;
  });

  return (
    <>
      <div className="min-h-screen bg-[#06060A] text-white">
        {/* Background */}
        <div className="fixed inset-0 pointer-events-none overflow-hidden z-0">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1400px] h-[900px]">
            <div className="absolute inset-0 bg-gradient-to-b from-[#00D4FF]/[0.06] via-[#3B82F6]/[0.03] to-transparent blur-3xl" />
          </div>
          <div className="absolute inset-0 bg-[linear-gradient(rgba(0,212,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(0,212,255,0.02)_1px,transparent_1px)] bg-[size:80px_80px]" />
        </div>

        {/* Header */}
        <div className="relative z-10 border-b border-white/[0.06]">
          <div className="max-w-6xl mx-auto px-4 sm:px-6 py-6">
            <div className="flex items-center justify-between">
              <div>
                <h1 className="font-display text-3xl font-light text-white mb-2">
                  Strategic <span className="nx-gradient-text">Briefs</span>
                </h1>
                <p className="text-white/40">
                  Institutional intelligence generated by our autonomous think tank
                </p>
              </div>
              <button
                onClick={() => setShowAuthModal(true)}
                className="px-6 py-3 rounded-xl bg-gradient-to-r from-[#00D4FF]/20 to-[#3B82F6]/20 border border-[#00D4FF]/20 text-white font-medium hover:border-[#00D4FF]/40 transition-all"
              >
                Get full access
              </button>
            </div>
          </div>
        </div>

        {/* Filters */}
        <div className="relative z-10 border-b border-white/[0.06]">
          <div className="max-w-6xl mx-auto px-4 sm:px-6 py-6">
            <div className="flex flex-col lg:flex-row gap-4 items-center justify-between">
              {/* Search */}
              <div className="relative flex-1 max-w-md">
                <Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/40" />
                <input
                  type="text"
                  placeholder="Search briefs..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-white/[0.08] bg-white/[0.02] text-white placeholder-white/40 focus:border-[#00D4FF]/40 focus:outline-none transition-all"
                />
              </div>

              {/* Type Filter */}
              <div className="flex gap-2">
                {[
                  { value: 'all', label: 'All Briefs' },
                  { value: 'executive', label: 'Executive' },
                  { value: 'strategic', label: 'Strategic' },
                ].map(filter => (
                  <button
                    key={filter.value}
                    onClick={() => setFilterType(filter.value as any)}
                    className={cn(
                      "px-4 py-2 rounded-lg border text-sm font-medium transition-all",
                      filterType === filter.value
                        ? "border-[#00D4FF]/40 bg-[#00D4FF]/10 text-[#00D4FF]"
                        : "border-white/[0.08] text-white/60 hover:border-white/[0.2]"
                    )}
                  >
                    {filter.label}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Briefs Grid */}
        <div className="relative z-10">
          <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8">
            {loading ? (
              <div className="text-center py-20">
                <div className="text-white/50">Loading briefs...</div>
              </div>
            ) : filteredBriefs.length === 0 ? (
              <div className="text-center py-20">
                <div className="text-white/50 mb-4">No briefs found</div>
                <button
                  onClick={() => {
                    setSearchTerm('');
                    setFilterType('all');
                  }}
                  className="text-[#00D4FF] hover:text-[#00D4FF]/80 transition-colors"
                >
                  Clear filters
                </button>
              </div>
            ) : (
              <>
                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
                  {filteredBriefs.map((brief) => (
                    <div key={brief.id} className="group rounded-2xl border border-white/[0.08] bg-gradient-to-br from-white/[0.03] to-white/[0.01] p-6 hover:border-[#00D4FF]/20 transition-all duration-300">
                      {/* Type Badge */}
                      <div className="flex items-center gap-2 mb-3">
                        <div className="w-2 h-2 rounded-full bg-[#00D4FF]"></div>
                        <span className="text-xs text-[#00D4FF]/60 uppercase tracking-wider">
                          {brief.type === 'STRATEGIC_REPORT' ? 'Strategic Report' : 'Executive Brief'}
                        </span>
                        <div className="ml-auto flex items-center gap-2 text-xs text-white/30">
                          <Clock size={12} />
                          {brief.readTime} min
                        </div>
                      </div>

                      {/* Title */}
                      <h3 className="font-display text-lg font-light text-white/90 mb-3 line-clamp-2 group-hover:text-[#00D4FF]/80 transition-colors">
                        {brief.title}
                      </h3>

                      {/* Summary */}
                      <p className="text-sm text-white/40 leading-relaxed mb-4 line-clamp-3">
                        {brief.summary}
                      </p>

                      {/* Meta */}
                      <div className="flex items-center justify-between text-xs text-white/30 mb-4">
                        <div className="flex items-center gap-3">
                          <span>{brief.sources} sources</span>
                          <span>•</span>
                          <span>{new Date(brief.publishedAt).toLocaleDateString()}</span>
                        </div>
                      </div>

                      {/* Topics */}
                      {brief.topics.length > 0 && (
                        <div className="flex flex-wrap gap-1 mb-4">
                          {brief.topics.slice(0, 3).map((topic, index) => (
                            <span key={index} className="text-xs px-2 py-1 rounded-full border border-white/[0.1] text-white/50">
                              {topic}
                            </span>
                          ))}
                          {brief.topics.length > 3 && (
                            <span className="text-xs px-2 py-1 rounded-full border border-white/[0.1] text-white/30">
                              +{brief.topics.length - 3}
                            </span>
                          )}
                        </div>
                      )}

                      {/* CTA */}
                      <button
                        onClick={() => handleReadFull(brief.id)}
                        className="w-full py-2.5 rounded-lg border border-[#00D4FF]/20 bg-[#00D4FF]/5 text-[#00D4FF] font-medium hover:bg-[#00D4FF]/10 transition-all group-hover:border-[#00D4FF]/40"
                      >
                        <span className="flex items-center justify-center gap-2">
                          Read full brief
                          <ArrowRight size={14} className="transition-transform group-hover:translate-x-1" />
                        </span>
                      </button>
                    </div>
                  ))}
                </div>

                {/* Pagination */}
                {totalPages > 1 && (
                  <div className="flex justify-center gap-2">
                    {Array.from({ length: totalPages }, (_, i) => i + 1).map(pageNum => (
                      <button
                        key={pageNum}
                        onClick={() => setPage(pageNum)}
                        className={cn(
                          "w-10 h-10 rounded-lg border text-sm font-medium transition-all",
                          page === pageNum
                            ? "border-[#00D4FF]/40 bg-[#00D4FF]/10 text-[#00D4FF]"
                            : "border-white/[0.08] text-white/60 hover:border-white/[0.2]"
                        )}
                      >
                        {pageNum}
                      </button>
                    ))}
                  </div>
                )}
              </>
            )}
          </div>
        </div>

        {/* Upgrade CTA Section */}
        <div className="relative z-10 border-t border-white/[0.06]">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 py-16">
            <div className="text-center p-10 sm:p-16 rounded-3xl border border-white/[0.08] bg-gradient-to-br from-white/[0.02] to-white/[0.01]">
              <div className="text-xs text-[#00D4FF]/50 tracking-[0.25em] uppercase mb-6">
                UNLOCK FULL INTELLIGENCE
              </div>
              
              <h2 className="font-display text-3xl sm:text-4xl font-light leading-tight mb-6">
                <span className="nx-gradient-text">Get complete access</span>
                <br />
                <span className="text-white/50 text-2xl sm:text-3xl">to every strategic insight</span>
              </h2>
              
              <div className="grid md:grid-cols-2 gap-8 mb-10 max-w-3xl mx-auto">
                <div className="text-left">
                  <h3 className="font-medium text-white/80 mb-3">Executive Briefs</h3>
                  <ul className="space-y-2 text-sm text-white/40">
                    <li>• Full 2-3 page analysis</li>
                    <li>• Complete source citations</li>
                    <li>• Decision-ready recommendations</li>
                    <li>• Weekly delivery</li>
                  </ul>
                </div>
                <div className="text-left">
                  <h3 className="font-medium text-white/80 mb-3">Strategic Reports</h3>
                  <ul className="space-y-2 text-sm text-white/40">
                    <li>• 10-15 page deep analysis</li>
                    <li>• Harvard Council insights</li>
                    <li>• Scenario planning</li>
                    <li>• Implementation roadmap</li>
                  </ul>
                </div>
              </div>
              
              <button
                onClick={() => setShowAuthModal(true)}
                className="group px-8 py-4 rounded-xl bg-gradient-to-r from-[#00D4FF]/20 to-[#3B82F6]/20 border border-[#00D4FF]/20 text-white font-medium hover:border-[#00D4FF]/40 transition-all shadow-[0_0_30px_rgba(0,212,255,0.15)]"
              >
                <span className="flex items-center justify-center gap-2">
                  Start 30-day free trial
                  <ArrowRight size={16} className="transition-transform group-hover:translate-x-1" />
                </span>
              </button>
              
              <div className="flex items-center justify-center gap-6 mt-8 text-xs text-white/40">
                <span>Executive: €15/month</span>
                <div className="w-1 h-1 rounded-full bg-[#00D4FF]/40" />
                <span>Strategy: €39/month</span>
                <div className="w-1 h-1 rounded-full bg-[#00D4FF]/40" />
                <span>No credit card required</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <AuthModal 
        isOpen={showAuthModal}
        onClose={() => setShowAuthModal(false)}
      />
    </>
  );
}
