import { Metadata } from 'next';
import Link from 'next/link';
import { NomosXLogo } from '@/components/brand/NomosXLogo';

export const metadata: Metadata = {
  title: 'Terms of Service | NomosX',
  description: 'NomosX Terms of Service',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#09090b] text-white">
      <div className="max-w-3xl mx-auto px-6 py-16">
        {/* Header */}
        <div className="mb-12">
          <Link href="/" className="inline-block mb-8">
            <NomosXLogo size="sm" variant="full" />
          </Link>
          <p className="text-xs text-indigo-400/80 font-semibold tracking-[0.2em] uppercase mb-3">Legal</p>
          <h1 className="text-4xl font-light text-white mb-3">Terms of Service</h1>
          <p className="text-sm text-white/40">Last updated: February 2026</p>
        </div>

        <div className="prose prose-invert prose-sm max-w-none space-y-8 text-white/70 leading-relaxed">

          <section>
            <h2 className="text-lg font-medium text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using NomosX ("the Service"), you agree to be bound by these Terms of Service.
              If you do not agree, do not use the Service. NomosX is operated by NomosX SAS.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-white mb-3">2. Description of Service</h2>
            <p>
              NomosX is an autonomous research intelligence platform. Our AI pipeline collects, analyzes,
              and publishes research briefs sourced from publicly available academic publications. The Service
              includes access to published briefs, a weekly intelligence dispatch, and (for paid tiers)
              the ability to commission custom research.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-white mb-3">3. User Accounts</h2>
            <p>
              You must provide accurate information when creating an account. You are responsible for
              maintaining the confidentiality of your credentials. You may not share your account or
              use the Service for any unlawful purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-white mb-3">4. Subscription & Billing</h2>
            <p>
              The Analyst tier is free. Researcher (€19/month) and Studio (€49/month) tiers are billed
              monthly via Stripe. Subscriptions renew automatically. You may cancel at any time from your
              dashboard; cancellation takes effect at the end of the current billing period.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-white mb-3">5. Intellectual Property</h2>
            <p>
              All content generated by NomosX (briefs, analyses, reports) is owned by NomosX SAS.
              You may use published briefs for personal or internal business purposes. Redistribution,
              resale, or republication without written permission is prohibited.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-white mb-3">6. Disclaimer of Warranties</h2>
            <p>
              The Service is provided "as is". NomosX does not warrant the accuracy, completeness, or
              fitness for any particular purpose of the content generated. Research briefs are produced
              by AI systems and should not be relied upon as professional legal, financial, or medical advice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-white mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, NomosX shall not be liable for any indirect,
              incidental, or consequential damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-white mb-3">8. Governing Law</h2>
            <p>
              These Terms are governed by French law. Any disputes shall be subject to the exclusive
              jurisdiction of the courts of Paris, France.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-white mb-3">9. Changes to Terms</h2>
            <p>
              We may update these Terms at any time. Continued use of the Service after changes
              constitutes acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-white mb-3">10. Contact</h2>
            <p>
              Questions about these Terms? Contact us at{' '}
              <a href="mailto:legal@nomosx.com" className="text-indigo-400 hover:text-indigo-300">
                legal@nomosx.com
              </a>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-white/10 flex gap-6 text-sm text-white/40">
          <Link href="/privacy" className="hover:text-white/70 transition-colors">Privacy Policy</Link>
          <Link href="/" className="hover:text-white/70 transition-colors">← Back to NomosX</Link>
        </div>
      </div>
    </div>
  );
}
